### ISSUE TITLE
Broken gopher index generation

### ISSUE THREAD

**Issue by spc476** [modgethanc/ttbp#37]
I'm trying to browse gopher://tilde.town/1/~endorphant/feels/ and all the entry links are broken.  The domain field only contains a 'tilde' and not 'tilde.town'.  This causes a DNS lookup failure and the page cannot be viewed outside of tilde.town.

**Comment by modgethanc** [comment]
@spc476 that's strange; i'm not getting this error, using lynx on debian from outside of tilde.town. can you give me more information about how you're accessing the gopher pages? what browser are you using?

**Comment by spc476** [comment]
At the time (Jan 15), the gopher index for the given page only had "tilde" in the host field, not "tilde.town".  The client at the time was mostly likely my own gopher client (on a machine that just crashed hard (to the point it no longer comes up) several hours ago).  I just checked the page, and the host field is now "tilde.town".  

I don't know what else to say.  I saw the problem, I reported it.  Perhaps there was a bug in the page generation code that you fixed shortly thereafter and the problem went away.

**Comment by modgethanc** [comment]
I think at that point, tilde.town was going through a big server migration that might have temporarily  broken some functions, including gopher indexing. I haven't touched the codebase for ttbp in quite some time (which is why it took me a while to get to this issue report). In any case, thanks for reporting it!
